#!/usr/bin/env python3
"""Establish-sequence PACE, measured on the wire's own clock, not the capture host's.

WHY NOT CAPTURE TIMESTAMPS. Two independent distortions sit on them:

  1. Capture-host scheduling (the usual caveat), and
  2. DECIMATION, which is far worse and is not obvious from the file. Audio
     arithmetic fixes the true frame rate: a 1492-byte frame is 52 + 40*36, the
     36-byte channel region is 12 samples of 24-bit audio, and 40ch x 48000 x 3 B
     = 5.76 MB/s / 1440 B = 4000 frames/s. Every real-desk MIRRORED capture in
     this corpus shows a 2 ms inter-frame gap -- i.e. 500 frames/s, one eighth of
     that. The mirror dropped 7 of every 8 frames. reac-pw's own captures were
     taken off a plain NIC ("clean") and are complete.

     So comparing raw inter-frame gaps between a real-desk mirrored capture and a
     reac-pw clean capture compares a decimated stream against a complete one and
     manufactures an 8x "pace difference" that is pure capture artifact.

THE INSTRUMENT INSTEAD. Every REAC frame carries a free-running u16 at offset 14
which the SENDER increments by 1 per frame. It is generated by the sender's own
media clock, so it survives both distortions: a dropped frame leaves a gap in the
sequence but does not change what the surviving frames say the time is.

  ticks/s = 4000 at 48k, 8000 at 96k -- verified across the corpus, and used here
  as the built-in control: a measurement that could not separate 48k from 96k
  could not separate anything.

Because each sender runs its OWN counter, box events are placed on the DESK's tick
axis by interpolating between the two adjacent desk frames. Capture timestamps are
therefore used only ACROSS ONE INTER-FRAME GAP (sub-millisecond in a clean
capture, ~2 ms in a decimated one) and never to time a long interval.

Usage: establish_pace.py <pcap> [<pcap> ...]
"""
import sys, os, bisect, statistics

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import reac_pcap as R

WRAP = 65536
WINDOW_MS = 4000.0
STOP_AFTER = 600_000


def unwrap_stream(seq):
    """[(ts, raw_u16)] -> [(ts, monotonic_tick)]; safe while gaps < wrap/2."""
    out, base, prev = [], 0, None
    for ts, v in seq:
        if prev is not None and v < prev - WRAP // 2:
            base += WRAP
        prev = v
        out.append((ts, v + base))
    return out


def classify(fr):
    """The establishment events, by control op."""
    ct = R.control(fr)
    if ct is None:
        return None
    kind, op, oplen = ct
    if kind == 'cfea':
        return 'MASTER-ANNOUNCE  cfea ffff 0100'
    if op == b'\x01\x03' and oplen == 0x000d:
        return 'ENROLL           cdea 0103 000d'
    if op == b'\x01\x03' and oplen == 0x0010:
        return 'BOX-CONFIG       cdea 0103 0010'
    if op == b'\x01\x03' and oplen == 0x0019:
        return 'CHANMAP          cdea 0103 0019'
    if op == b'\x04\x03' and oplen in (0x0016, 0x001a):
        return 'BOX-JOIN         cdea 0403 %04x' % oplen
    if op == b'\x04\x03' and oplen == 0x0013:
        rec = R.dt1_record(fr)
        if rec and rec.get('inner_ok') and rec['tag'] == '0101':
            return 'HEADAMP-REC      cdea 0403 0013 [0101]'
        return 'DT1-OTHER        cdea 0403 0013'
    return None


def scan(path):
    desk_seq, events, lens = {}, [], {}
    for i, (ts, wl, fr) in enumerate(R.iter_packets(path)):
        if i > STOP_AFTER:
            break
        if not R.is_reac(fr):
            continue
        src = R.mac(fr[6:12])
        tick = int.from_bytes(fr[14:16], 'little')
        desk_seq.setdefault(src, []).append((ts, tick))
        lens.setdefault(src, set()).add(len(fr))
        lab = classify(fr)
        if lab:
            events.append((ts, src, lab))
    return desk_seq, events, lens


def tick_rate(stream_uw):
    """ticks/sec, from the median of ALL adjacent pairs (no dt band filter --
    a band that excludes the dominant inter-frame gap biases the answer)."""
    rates = []
    for i in range(1, len(stream_uw)):
        dt = stream_uw[i][0] - stream_uw[i - 1][0]
        dk = stream_uw[i][1] - stream_uw[i - 1][1]
        if 0 < dt < 0.05 and 0 < dk < 500:
            rates.append(dk / dt)
    return statistics.median(rates) if len(rates) >= 50 else None


def report(path):
    base = os.path.basename(path)
    desk_seq, events, lens = scan(path)
    if not events:
        print(f'\n=== {base} ===\n  (no establishment events)')
        return
    # the master is the source of the 1492-byte downstream braid with the most frames
    master = max(desk_seq, key=lambda s: (max(lens[s]) >= 1492, len(desk_seq[s])))
    uw = unwrap_stream(desk_seq[master])
    rate = tick_rate(uw)
    ts_axis = [t for t, _ in uw]

    def to_ms(ts):
        """capture ts -> desk wire-tick, in ms, by LOCAL interpolation only."""
        j = bisect.bisect_left(ts_axis, ts)
        if j <= 0:
            j = 1
        if j >= len(uw):
            j = len(uw) - 1
        (t0, k0), (t1, k1) = uw[j - 1], uw[j]
        k = k0 if t1 == t0 else k0 + (k1 - k0) * (ts - t0) / (t1 - t0)
        return k / rate * 1000.0

    print(f'\n=== {base} ===')
    obs = 1.0 / statistics.median(
        [uw[i][0] - uw[i - 1][0] for i in range(1, min(len(uw), 3000))]) if len(uw) > 50 else 0
    print(f'  master={master}  ticks/s={rate:.1f}  observed frames/s={obs:.0f}'
          f'  -> capture keeps ~1 in {4000 / obs if obs else 0:.1f} frames' if rate else '  (rate unknown)')
    anchor = None
    for ts, src, lab in events:
        if lab.startswith('BOX-CONFIG') or lab.startswith('BOX-JOIN'):
            anchor = ts
            break
    a_ms = to_ms(anchor) if anchor is not None else to_ms(events[0][0])
    # Only the window AROUND the establishment. In a capture that ran for minutes
    # before the box appeared, "first occurrence in file" is steady-state traffic
    # and says nothing about the establish sequence.
    lo, hi = -WINDOW_MS, WINDOW_MS
    shown = 0
    for ts, src, lab in events:
        rel = to_ms(ts) - a_ms
        if not (lo <= rel <= hi):
            continue
        side = 'BOX ' if src != master else 'DESK'
        print(f'   {rel:+10.1f} ms  {side} {lab}')
        shown += 1
        if shown >= 40:
            print('   ... (truncated)')
            break


for p in sys.argv[1:]:
    try:
        report(p)
    except Exception as e:
        print(f'\n=== {os.path.basename(p)} ===\n  ERROR {e}')
