#!/usr/bin/env python3
"""Validate reac.ksy's chanmap grammar -- including the new group-anchor
instances -- against the real captures rather than against the firmware image.

A grammar derived from a decompilation is a hypothesis. This runs the parser ksc
generates from reac.ksy over every chanmap frame in the corpus and checks that
what the grammar SAYS matches what real consoles and reac-pw actually send.

Checks, all of them falsifiable:

  1. every chanmap page parses, page_id == 1, 8 entries of 3 bytes
  2. slot ids come only from the 49-position ring (0x00..0x2f plus 0xfe)
  3. is_group_anchor is true exactly on slots 0x00,0x04,...,0x2c -- and never on
     the 0xfe wrap marker
  4. group == slot >> 2 and lands in 0..11
  5. cell_type is analog_input for groups 0..9 and absent for groups 10..11,
     on EVERY console generation and EVERY box model
  6. the whole ring is emitted -- i.e. the sweep is complete, not a subset

KNOWN-POSITIVE CONTROL (check 7): the corpus must contain both cell_type values
and both 0xfe sentinel values. A run that saw only one of each would mean the
scan was too narrow to justify any claim of uniformity, and is reported as
INCONCLUSIVE rather than PASS.

Usage:
  PYTHONPATH=<reac-protocol/spec> ksy_chanmap_validate.py
"""
import sys, os, glob, collections

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import reac_pcap as R

SPEC = os.environ.get('REAC_SPEC', '/home/pau/Devel/audio/reac-protocol/spec')
sys.path.insert(0, SPEC)
from reac import Reac                                     # generated by ksc
import kaitaistruct
from io import BytesIO

MAX_CHANMAP_PER_FILE = 400
RING = set(range(0x00, 0x30)) | {0xFE}
ANCHORS = {s for s in range(0x00, 0x30) if s % 4 == 0}


def console_of(base):
    return base.split('__')[0].split('-')[0]


def box_of(base):
    p = base.split('__')[0].split('-')
    return p[1] if len(p) > 1 else '?'


def main():
    files = sorted(glob.glob('/home/pau/Devel/audio/reac-captures/**/*.pcap', recursive=True))
    fails = collections.Counter()
    examples = collections.defaultdict(list)
    seen_cell = collections.defaultdict(set)      # (console,box) -> {(group,cell_type)}
    slots_seen = collections.defaultdict(set)     # (console,box) -> slots
    sentinel_vals = collections.Counter()
    truncated = collections.Counter()
    n_pages = 0
    n_files = 0

    for path in files:
        base = os.path.basename(path)
        key = (console_of(base), box_of(base), 'OURS' if 'reacpw' in base else 'REAL')
        got = 0
        try:
            for ts, wl, fr in R.iter_packets(path):
                if not R.is_reac(fr):
                    continue
                if wl > len(fr):
                    # SNAPLEN-TRUNCATED capture: tcpdump stored fewer bytes than
                    # the wire carried. Not a protocol variant and not a grammar
                    # defect -- the grammar SHOULD refuse these. Counted, skipped.
                    #
                    # The trap worth naming: 52 + 18*36 == 700, so a 1492-byte
                    # frame truncated to a 700-byte snaplen passes canonical_len()
                    # as a legal 18-channel frame. Only the trailing end_marker
                    # catches it, which is exactly what it did here.
                    truncated[base] += 1
                    continue
                ct = R.control(fr)
                if not ct or ct[1] != b'\x01\x03' or ct[2] != 0x19:
                    continue
                try:
                    p = Reac(kaitaistruct.KaitaiStream(BytesIO(fr)))
                    page = p.control.block.payload.page
                except Exception as e:
                    fails['parse_error'] += 1
                    examples['parse_error'].append(f'{base}: {e!r}')
                    got += 1
                    continue
                n_pages += 1
                got += 1
                if page.page_id != 1:
                    fails['page_id!=1'] += 1
                if len(page.entries) != 8:
                    fails['entries!=8'] += 1
                for e in page.entries:
                    if e.slot not in RING:
                        fails['slot_off_ring'] += 1
                        examples['slot_off_ring'].append(f'{base}: slot={e.slot:#04x}')
                        continue
                    slots_seen[key].add(e.slot)
                    if e.slot == 0xFE:
                        sentinel_vals[e.bank] += 1
                        if e.is_group_anchor:
                            fails['sentinel_is_anchor'] += 1
                            examples['sentinel_is_anchor'].append(base)
                        continue
                    expect_anchor = e.slot in ANCHORS
                    if bool(e.is_group_anchor) != expect_anchor:
                        fails['anchor_mismatch'] += 1
                        examples['anchor_mismatch'].append(f'{base}: slot={e.slot:#04x}')
                    if not expect_anchor:
                        continue
                    if e.group != e.slot >> 2 or not (0 <= e.group <= 11):
                        fails['group_bad'] += 1
                    seen_cell[key].add((e.group, e.cell_type.value if hasattr(e.cell_type, 'value')
                                        else int(e.cell_type)))
                if got >= MAX_CHANMAP_PER_FILE:
                    break
        except Exception as e:
            fails['file_error'] += 1
            examples['file_error'].append(f'{base}: {e!r}')
        if got:
            n_files += 1

    print(f'parsed {n_pages} chanmap pages from {n_files} captures')
    if truncated:
        print(f'skipped {sum(truncated.values())} frames in {len(truncated)} SNAPLEN-TRUNCATED '
              f'captures (wire len > captured len): {", ".join(sorted(truncated))}')
    print()

    print('=== per (console, box, side): groups -> cell_type, and ring completeness ===')
    NAME = {2: 'analog_input', 3: 'absent'}
    inconsistent = []
    for key in sorted(seen_cell):
        pairs = dict(sorted(seen_cell[key]))
        ring_ok = slots_seen[key] >= RING
        line = ' '.join(f'g{g}={NAME.get(c, c)[:5]}' for g, c in sorted(pairs.items()))
        print(f'  {key[2]} {key[0]:10} {key[1]:7} full_ring={"Y" if ring_ok else "N"}  {line}')
        exp = {g: (2 if g <= 9 else 3) for g in range(12)}
        if pairs and any(pairs.get(g) not in (None, exp[g]) for g in pairs):
            inconsistent.append((key, pairs))

    print('\n=== CONTROL (check 7): did the scan see enough variety to claim uniformity? ===')
    all_cells = {c for v in seen_cell.values() for _, c in v}
    print(f'   distinct cell_type values observed : {sorted(all_cells)} '
          f'{"OK - both present" if all_cells >= {2, 3} else "TOO NARROW"}')
    print(f'   distinct 0xfe sentinel values      : {sorted(sentinel_vals)} '
          f'{"OK - both present" if len(sentinel_vals) >= 2 else "TOO NARROW"}')
    print(f'   distinct (console,box,side) groups  : {len(seen_cell)}')

    print('\n=== FAILURES ===')
    if not fails:
        print('   none')
    for k, v in fails.most_common():
        print(f'   {k}: {v}')
        for ex in examples[k][:3]:
            print(f'      e.g. {ex}')
    if inconsistent:
        print('\n   cell_type deviating from groups 0-9=analog_input / 10-11=absent:')
        for key, pairs in inconsistent:
            print(f'      {key}: {pairs}')

    ok = not fails and not inconsistent and all_cells >= {2, 3} and len(sentinel_vals) >= 2
    print(f'\nVERDICT: {"PASS - grammar matches every real capture" if ok else "SEE ABOVE"}')
    return 0 if ok else 1


sys.exit(main())
